import './globals.css'
import Header from '@/app/components/header'
import { Poppins } from "next/font/google"
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const poppins = Poppins({ subsets: ['latin'],weight:["400","600"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />  
        <main className='container'>
          <ToastContainer />
          {children}
        </main>
      </body>
    </html>
  )
}
